---
- name: 1.Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
 
- name: 2.Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
 
- name: 3.Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists

- name: Download OpenVPNAS
  get_url:
    url:  http://swupdate.openvpn.org/as/openvpn-as-2.5.2-CentOS7.x86_64.rpm
    dest: /root/openvpn.rpm

- name: install nginx rpm from a local file
  yum:
    name: /root/openvpn.rpm
    state: present
    
- selinux:
    state: disabled
- name: Allow http/https
  command: firewall-cmd --zone=public --permanent --add-service=http --add-service=https 

# - name: LAN magic
  # shell: firewall-cmd --zone=trusted --add-interface=tun0   
# - name: LAN magic
  # shell: echo 1 > /proc/sys/net/ipv4/ip_forward  
# - name: LAN magic
  # shell: ip addr flush dev tap0  
# - name: LAN magic
  # shell: ip route add 192.168.1.0/24 via {{ lanip }}
# - name: 9. OpenVPN service
  # service: name=openvpn@client.service state=restarted enabled=yes  
  #ip addr flush dev tap0
  # ip route add 192.168.1.0/24 via 192.168.1.42
  # firewall-cmd --zone=trusted --add-interface=tun0
  # echo 1 > /proc/sys/net/ipv4/ip_forward